#!/usr/bin/env perl
use Modern::Perl;

# Create an array of three letter abbreviations of English month
# names.  Loop over the elements of the array and assign each month
# its corresponding ordinal. Demonstrate that calling $months{'Jan'}
# and $months{'Dec'} print out the correct ordinal number.

my @months;
my %months;







say "Ordinal of January is ", $months{'Jan'};
say "Ordinal of December is ", $months{'Dec'};

